[webuser@control-node web_ansible]$ cat web-target.yml
---
- name: Automated Web Server Deployment
  hosts: webserver
  become: yes
  tasks:
    - name: Install Apache HTTPD
      yum:
        name: httpd
        state: latest

    - name: Start and Enable Apache Service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create Custom Landing Page
      copy:
        content: "<h1>The webserver deployed successfully</h1>"
        dest: /var/www/html/index.html

    - name: Configure Firewall for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
